"""initial schema

Revision ID: c5c750828c71
Revises: 
Create Date: 2026-06-27 08:23:59.320877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'c5c750828c71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_name'), 'clinics', ['name'], unique=False)
    op.create_index(op.f('ix_clinics_source_name'), 'clinics', ['source_name'], unique=False)
    op.create_table('parse_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_saved', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parse_runs_source_name'), 'parse_runs', ['source_name'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=256), nullable=False),
    sa.Column('old_price', sa.Integer(), nullable=True),
    sa.Column('new_price', sa.Integer(), nullable=True),
    sa.Column('percent_change', sa.Float(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_source_key'), 'price_history', ['source_key'], unique=False)
    op.create_table('raw_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', 'content_hash', name='uq_raw_doc_url_hash')
    )
    op.create_index(op.f('ix_raw_documents_source_name'), 'raw_documents', ['source_name'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_key', sa.String(length=32), nullable=False),
    sa.Column('name_ru', sa.String(length=512), nullable=False),
    sa.Column('category', sa.Enum('лаборатория', 'приём врача', 'диагностика', 'процедура', name='service_category'), nullable=False),
    sa.Column('specialty', sa.String(length=256), nullable=True),
    sa.Column('tarificatr_code', sa.String(length=64), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_name_ru'), 'services', ['name_ru'], unique=False)
    op.create_index(op.f('ix_services_service_key'), 'services', ['service_key'], unique=True)
    op.create_table('clinic_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('working_hours', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_branches_city'), 'clinic_branches', ['city'], unique=False)
    op.create_index(op.f('ix_clinic_branches_clinic_id'), 'clinic_branches', ['clinic_id'], unique=False)
    op.create_table('raw_price_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('clinic_raw', sa.String(length=256), nullable=True),
    sa.Column('service_name_raw', sa.String(length=512), nullable=False),
    sa.Column('price_raw', sa.String(length=64), nullable=True),
    sa.Column('duration_raw', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_price_items_raw_document_id'), 'raw_price_items', ['raw_document_id'], unique=False)
    op.create_table('service_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_aliases_alias'), 'service_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_service_aliases_service_id'), 'service_aliases', ['service_id'], unique=False)
    op.create_table('clinic_service_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('raw_price_item_id', sa.Integer(), nullable=True),
    sa.Column('price_kzt', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('duration_max', sa.Integer(), nullable=True),
    sa.Column('service_name_raw', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['clinic_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_price_item_id'], ['raw_price_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_service_prices_clinic_id'), 'clinic_service_prices', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinic_service_prices_is_active'), 'clinic_service_prices', ['is_active'], unique=False)
    op.create_index(op.f('ix_clinic_service_prices_parsed_at'), 'clinic_service_prices', ['parsed_at'], unique=False)
    op.create_index(op.f('ix_clinic_service_prices_service_id'), 'clinic_service_prices', ['service_id'], unique=False)
    op.create_table('unmatched_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=True),
    sa.Column('raw_name', sa.String(length=512), nullable=False),
    sa.Column('suggested_service_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_price_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.create_index(
        "ix_services_name_ru_trgm",
        "services",
        ["name_ru"],
        postgresql_using="gin",
        postgresql_ops={"name_ru": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_service_aliases_alias_trgm",
        "service_aliases",
        ["alias"],
        postgresql_using="gin",
        postgresql_ops={"alias": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_active_prices_lookup",
        "clinic_service_prices",
        ["service_id", "price_kzt", "parsed_at"],
        postgresql_where=sa.text("is_active"),
    )


def downgrade() -> None:
    op.drop_index("ix_active_prices_lookup", table_name="clinic_service_prices")
    op.drop_index("ix_service_aliases_alias_trgm", table_name="service_aliases")
    op.drop_index("ix_services_name_ru_trgm", table_name="services")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unmatched_services')
    op.drop_index(op.f('ix_clinic_service_prices_service_id'), table_name='clinic_service_prices')
    op.drop_index(op.f('ix_clinic_service_prices_parsed_at'), table_name='clinic_service_prices')
    op.drop_index(op.f('ix_clinic_service_prices_is_active'), table_name='clinic_service_prices')
    op.drop_index(op.f('ix_clinic_service_prices_clinic_id'), table_name='clinic_service_prices')
    op.drop_table('clinic_service_prices')
    op.drop_index(op.f('ix_service_aliases_service_id'), table_name='service_aliases')
    op.drop_index(op.f('ix_service_aliases_alias'), table_name='service_aliases')
    op.drop_table('service_aliases')
    op.drop_index(op.f('ix_raw_price_items_raw_document_id'), table_name='raw_price_items')
    op.drop_table('raw_price_items')
    op.drop_index(op.f('ix_clinic_branches_clinic_id'), table_name='clinic_branches')
    op.drop_index(op.f('ix_clinic_branches_city'), table_name='clinic_branches')
    op.drop_table('clinic_branches')
    op.drop_index(op.f('ix_services_service_key'), table_name='services')
    op.drop_index(op.f('ix_services_name_ru'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_raw_documents_source_name'), table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_index(op.f('ix_price_history_source_key'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_parse_runs_source_name'), table_name='parse_runs')
    op.drop_table('parse_runs')
    op.drop_index(op.f('ix_clinics_source_name'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_name'), table_name='clinics')
    op.drop_table('clinics')
    # ### end Alembic commands ###
